name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      # - name: Check license headers
      #   run: deno task check:license --check

      - name: Run tests
        run: deno task test
